version: '3.8'

services:
  svm-service:
    build:
      context: ./svm_service
    container_name: svm_service
    image: salmalafiii23/svm-service:latest  # Specify image name here
    ports:
      - "5000:5000"

  vgg19-service:
    build:
      context: ./vgg19_service
    container_name: vgg19_service
    image: salmalafiii23/vgg19-service:latest  # Specify image name here
    ports:
      - "5002:5002"

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    image: salmalafiii23/frontend:latest  # Specify image name here
    ports:
      - "5001:5001"
