version: '3.8'

services:
  svm-service:
    build:
      context: ./svm_service
    container_name: svm_service
    ports:
      - "5000:5000"   

   
  vgg19-service:
    build:
      context: ./vgg19_service
    container_name: vgg19_service
    ports:
      - "5002:5002"
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "5001:5001"
